- name: Backup Pi-hole Configuration
  hosts: pihole_server
  gather_facts: false
  become: yes

  tasks:
    - name: Retrieve the current time in order to timestamp files
      ansible.builtin.setup:
        gather_subset:
        - date_time
      delegate_to: localhost

    - name: Delete any existing pihole backup directory
      file:
        path: /tmp/pihole_backup
        state: absent 

    - name: Ensure backup directory exists
      file:
        path: /tmp/pihole_backup
        state: directory

    - name: Copy Pi-hole configurations to backup directory
      command: sh -c 'cp -r /var/lib/docker/volumes/etc_pihole/_data/* /tmp/pihole_backup/'
  

    - name: Archive backup directory
      command: tar czf /tmp/pihole_backup.tar.gz -C /tmp pihole_backup

    - name: Fetch backup to local machine
      ansible.posix.synchronize:
        src: /tmp/pihole_backup.tar.gz
        dest: /tmp/pihole_backup.{{ ansible_date_time.iso8601_basic_short }}.tar.gz
        mode: pull
    
    - name: Delete pihole backup directory
      file:
        path: /tmp/pihole_backup
        state: absent 

    - name: Delete pihole backup archive
      file:
        path: /tmp/pihole_backup.tar.gz
        state: absent 