---
- name: Full update of Ubuntu on Raspberry Pi
  hosts: office_pis
  # hosts: ubuntu-server-1
  become: true
  gather_facts: true
  serial: 1

  vars:
    apt_env:
      DEBIAN_FRONTEND: noninteractive
    reboot_timeout_seconds: 600
    # Set to true if you want to automatically unhold any held packages
    unhold_packages: false

  pre_tasks:
    - name: Ensure we can reach the host
      ansible.builtin.ping:

  tasks:
    - name: Refresh apt cache + full upgrade
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist
      environment: "{{ apt_env }}"

    - name: Ensure kernel/firmware latest
      ansible.builtin.apt:
        name:
          - linux-raspi
          - linux-firmware
        state: latest
      environment: "{{ apt_env }}"

    - name: Autoremove unused packages
      ansible.builtin.apt:
        autoremove: yes
        purge: yes
      environment: "{{ apt_env }}"

    - name: Clean apt caches
      ansible.builtin.apt:
        autoclean: yes
        clean: yes
      environment: "{{ apt_env }}"

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if needed
      ansible.builtin.reboot:
        reboot_timeout: "{{ reboot_timeout_seconds }}"
      when: reboot_required.stat.exists

    - name: Report kernel and OS version
      ansible.builtin.shell: "echo $(uname -r) $(lsb_release -ds)"
      register: system_report
      changed_when: false

    - name: Show report
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}: {{ system_report.stdout }}"