---
- name: Pi-hole Teleporter Backup and Move
  hosts: pihole_server
  gather_facts: false

  vars_files:
    - ["custom.config.yml", "default.config.yml"]
    - ./credentials/nas1.yml
  
  tasks:

    - name: Retrieve the current time in order to timestamp files
      ansible.builtin.setup:
        gather_subset:
          - date_time

    - name: Remove existing Teleporter backup files
      ansible.builtin.shell: 'docker exec {{ pihole_container_id }} find / -type f -name "pi-hole_*.zip" -exec rm -f {} \; 2>/dev/null'
      ignore_errors: true  # Ignore errors if no files are found or due to permission issues

    - name: Execute Teleporter backup in Pi-hole container
      ansible.builtin.shell: "docker exec -w / {{ pihole_container_id }} pihole-FTL --teleporter"
      register: backup_output
      async: 300
      poll: 5

    - name: Locate the latest Teleporter backup file
      ansible.builtin.shell: 'docker exec {{ pihole_container_id }} find / -type f -name "pi-hole_*.zip" 2>/dev/null'
      register: backup_file_location
      changed_when: false
      failed_when: backup_file_location.rc != 0 and backup_file_location.stdout == ""

    - name: Set backup filename without leading slash
      ansible.builtin.set_fact:
        backup_file_no_leading_slash: "{{ backup_file_location.stdout | regex_replace('^/', '') }}"

    - name: Debug backup file path without leading slash
      ansible.builtin.debug:
        msg: "Cleaned backup file path: {{ backup_file_no_leading_slash }}"

    - name: Copy backup file from Docker container to host
      ansible.builtin.shell: "docker cp {{ pihole_container_id }}:/{{ backup_file_no_leading_slash  }} /tmp/{{ backup_file_no_leading_slash  }}"
      async: 300
      poll: 5

    - name: Fetch backup file to local machine
      ansible.builtin.fetch:
        src: /tmp/{{ backup_file_no_leading_slash  }}
        dest: /tmp/{{ backup_file_no_leading_slash  }}
        flat: yes
      timeout: 600

    - name: Remove backup file from Docker container
      ansible.builtin.shell: "docker exec {{ pihole_container_id }} rm /{{ backup_file_no_leading_slash  }}"
      async: 300
      poll: 5

    - name: Upload Pihole backup to Synology NAS via SCP
      ansible.builtin.shell: >
        scp -O -i {{ nas1_private_key }}
        "/tmp/{{ backup_file_no_leading_slash  }}"
        {{ nas1_username }}@{{ nas1_hostname }}:{{ nas1_pihole_directory }}/
      delegate_to: localhost
      register: scp_result
      failed_when: scp_result.rc != 0

    - name: Delete local copy of the backup
      ansible.builtin.file:
        path: "/tmp/{{ backup_file_no_leading_slash  }}"
        state: absent
      delegate_to: localhost

    - name: Delete remote copy of the backup
      ansible.builtin.file:
        path: "/tmp/{{ backup_file_no_leading_slash  }}"
        state: absent