---
- name: Update and Upgrade Raspberry Pi
  hosts: internal
  become: yes
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Upgrade all apt packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Reboot the system if necessary
      reboot:
        msg: "Reboot initiated by Ansible for updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami