---
- name: Edge Router Backup
  hosts: edge_router
  gather_facts: false

  vars_files:
    - ["custom.config.yml", "default.config.yml"]
    - ./credentials/nas1.yml
  
  
  tasks:

    - name: Retrieve the current time in order to timestamp files
      ansible.builtin.setup:
        gather_subset:
        - date_time
      delegate_to: localhost

    - name: "Transfer {{ router_remote_file }} from router, using SCP with password"
      ansible.builtin.expect:
        command: "scp -o StrictHostKeyChecking=no {{ ansible_user }}@{{ ansible_host }}:{{ router_remote_file }} /tmp/config.boot.{{ ansible_date_time.iso8601_basic_short }}"
        responses:
          password: "{{ ansible_ssh_pass }}"
      delegate_to: localhost
      
    - name: Upload Edge Router backup to Synology NAS via SCP
      ansible.builtin.shell: >
        scp -O -i {{ nas1_private_key }}
        /tmp/config.boot.{{ ansible_date_time.iso8601_basic_short }}
        {{ nas1_username }}@{{ nas1_hostname }}:{{ nas1_router_directory }}/
      delegate_to: localhost
      register: scp_result
      failed_when: scp_result.rc != 0

    - name: "Remove local /tmp/config.boot.{{ ansible_date_time.iso8601_basic_short }}"
      ansible.builtin.file:
        path: "/tmp/config.boot.{{ ansible_date_time.iso8601_basic_short }}"
        state: absent
      delegate_to: localhost