---
- name: Unifi Backup and Move
  hosts: unifi_server
  gather_facts: false

  vars_files:
    - ["custom.config.yml", "default.config.yml"]
    - ./credentials/nas1.yml
  
  tasks:

    - name: Retrieve the current time in order to timestamp files
      ansible.builtin.setup:
        gather_subset:
          - date_time
      delegate_to: localhost

    - name: Find the most recently created .unf file in the unifi container
      ansible.builtin.shell: >
        docker exec {{ unifi_container_id }} /bin/bash -c 'find {{ unifi_container_autobackup_dir }} -type f -name "*.unf" -printf "%T@ %p\n" | sort -n | tail -1 | cut -f2- -d" " || echo "No .unf files found"'
      register: recent_file
      changed_when: false

    - name: Debug recent file path
      ansible.builtin.debug:
        msg: "The most recent backup file path is {{ recent_file.stdout }}"

    - name: Copy backup file from Docker container to host
      ansible.builtin.shell: >
        docker cp {{ unifi_container_id }}:"{{ recent_file.stdout }}" /tmp/unifi_controller_backup.{{ ansible_date_time.iso8601_basic_short }}.unf

    - name: Fetch backup file to local machine
      ansible.builtin.fetch:
        src: /tmp/unifi_controller_backup.{{ ansible_date_time.iso8601_basic_short }}.unf
        dest: /tmp/unifi_controller_backup.{{ ansible_date_time.iso8601_basic_short }}.unf
        flat: yes

    - name: Upload UniFi backup to Synology NAS via SCP
      ansible.builtin.shell: >
        scp -O -i {{ ansible_env.HOME }}/{{ nas1_private_key }}
        "/tmp/unifi_controller_backup.{{ ansible_date_time.iso8601_basic_short }}.unf"
        {{ nas1_username }}@{{ nas1_hostname }}:{{ nas1_unifi_directory }}/
      delegate_to: localhost
      register: scp_result
      failed_when: scp_result.rc != 0

    - name: Delete local copy of the backup
      ansible.builtin.file:
        path: "/tmp/unifi_controller_backup.{{ ansible_date_time.iso8601_basic_short }}.unf"
        state: absent
      delegate_to: localhost

    - name: Delete remote copy of the backup
      ansible.builtin.file:
        path: "/tmp/unifi_controller_backup.{{ ansible_date_time.iso8601_basic_short }}.unf"
        state: absent
      delegate_to: localhost